### ISSUE TITLE
How to train with other language ?

### ISSUE THREAD

**Issue by ThorPham** [jarobyte91/post_ocr_correction#1]
Thank for your great paper . I want to train with my language. Could you tell me some step prepare dataset to train. Thank a lot

**Comment by jarobyte91** [comment]
You will need to have the raw input and the reference transcription aligned like in the [ICDAR 2019 competition](https://sites.google.com/view/icdar2019-postcorrectionocr/dataset?authuser=0). Figure 5 in the [paper](https://arxiv.org/pdf/2109.06264.pdf) describes how to train the sequence-to-sequence model.

Look at the [notebooks](https://github.com/jarobyte91/post_ocr_correction/tree/master/notebooks/bg) folder to see the data pipeline for each of the languages.

You may also be interested in the updated version of the [library](https://github.com/jarobyte91/pytorch_beam_search) I used to train the sequence models.

The code below should do the trick to align the input and the reference

    from nltk.metrics.distance import edit_distance_align as d

    def align(s1, s2, fill = "@"):
        mapping = d(s1, s2, substitution_cost = 2)
        o1, o2 = "", ""
        for i, (a, b) in enumerate(mapping[1:], 1):
            if mapping[i - 1][0] == a or i - 1 < 0 :
                o1 += fill
            else:
                o1 += s1[a - 1]
            
            if mapping[i - 1][1] == b or i - 1 < 0 :
                o2 += fill
            else:
                o2 += s2[b - 1]
        print(o1)
        print(o2)
        return o1, o2

    # sample input
    align("INEVR jrlf Major Long ow.", "I NEVER Major Longhow.")

    # sample output
    ('I@NEV@R jrlf Major Long ow.', 'I NEVER @@@@@Major Longhow.')

**Comment by ThorPham** [comment]
Thank for your help . It's can train with word not sentences

**Comment by jarobyte91** [comment]
Maybe you can translate this with Google Translate? You can train the sequence-to-sequence models with words, but it's best if you train them with n-grams, like in the paper.

**Comment by ThorPham** [comment]
Thank a lot i will try

**Comment by trantuankhoi** [comment]
hi bác @ThorPham 

Không biết bác đã train được chưa nhỉ, nếu được thì bác cho em xin checkpoint của bác để thử nghiệm được không ạ

Em cảm ơn
