### ISSUE TITLE
Will you able to share the pretrained model?

### ISSUE THREAD

**Issue by Yuying-W** [jarobyte91/post_ocr_correction#2]
I am impressed by you paper. Thank you for your great work.
Do you mind to share your pretrained model, so I can play with it.

**Comment by jarobyte91** [comment]
This repository uses Git Large File Storage (Git LFS) to store the weights of the pre-trained models. They should populate the **data** folder. Check the installation part of the README to see how to install it. If that doesn't work, let me know on this issue.
