### ISSUE TITLE
ModuleNotFoundError: No module named 'pytorch_decoding'

### ISSUE THREAD

**Issue by xuqinkun** [jarobyte91/post_ocr_correction#5]
![image](https://user-images.githubusercontent.com/19572081/217992886-280e7ea4-7ccb-4cb9-abb7-e26377c3a264.png)

I install the project by your instructions. But I can't find the module 'pytorch_decoding'.

**Comment by jarobyte91** [comment]
The code from the notebooks is very outdated, so the best way to use this project is to follow the examples in the README. What you are trying to run is an earlier version of the library, so you should be good to go by subtituting

pytorch_decoding.seq2seq   =>  pytorch_beam_search.seq2seq
