### ISSUE TITLE
evaluate_model

### ISSUE THREAD

**Issue by xuqinkun** [jarobyte91/post_ocr_correction#6]
from ocr_correction import evaluate_model

**Comment by jarobyte91** [comment]
The code from the notebooks is very outdated, so the best way to use this project is to follow the examples in the README. Can you tell me where did you find this?

**Comment by jarobyte91** [comment]
probably what you need to do is subtitute 

    from ocr_correction import evaluate_model

with

    from post_ocr_correction.correction import full_evaluation

**Comment by xuqinkun** [comment]
Got it. Thanks!
