### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by xuqinkun** [jarobyte91/post_ocr_correction#7]
I have noticed that after using your method to correct the text, the CER in English is below the baseline.  Why is this happening?
![image](https://user-images.githubusercontent.com/19572081/218234587-414caced-95c4-4690-b68f-7d45a6ae790f.png)
Also, as you mentioned in the section of Discussion, the weight function doesn't seem to be very useful. Have you considered using other weight functions, such as introducing word frequency?
![image](https://user-images.githubusercontent.com/19572081/218234634-b0e17dc6-bb1b-4f54-92d4-5bcd3e6f9040.png)

**Comment by jarobyte91** [comment]
Yes, in some languages, the results we obtained were below the baseline, but our method is very fast, easy to train and language-independent. Also, notice from Table 1 that we obtained this results with as few as 200 documents.

I don't see how you can build a weighting function using word frequency: remember that the weighting function is what determines the weight of each character in each n-gram when you join them together.

**Comment by xuqinkun** [comment]
The idea of using word frequency to calculate the weight function came from [OCR error correction using correction patterns and self‑organizing migrating algorithm](https://link.springer.com/article/10.1007/s10044-020-00936-y). Besides, I hava a question about the challenge of Post-OCR Text Correction. Why doesn't the authorities provide the image data?  I think image features are crucial for OCR text correction tasks. Is there any way to get the image data?

**Comment by xuqinkun** [comment]
[Challenge ICDAR2019 Competition on Post-OCR Text Correction](https://sites.google.com/view/icdar2019-postcorrectionocr)

**Comment by jarobyte91** [comment]
The whole purpose of the competition is to correct text when the documents have already been scanned and the image of the document itself has been lost. There is no way to obtain the image data for that particular competition.

**Comment by xuqinkun** [comment]
Got it

**Comment by Alexsong111** [comment]
> Got it

Hi Qingkun, do you know how to do all the training all over again? Did you try it?

The author said we can go to notebooks, but the code is outdate and we need to change many things. Have you already change the code in notebooks? Thanks!

**Comment by xuqinkun** [comment]
> > Got it
> 
> Hi Qingkun, do you know how to do all the training all over again? Did you try it?
> 
> The author said we can go to notebooks, but the code is outdate and we need to change many things. Have you already change the code in notebooks? Thanks!

Try this https://github.com/xuqinkun/post_ocr_correction

**Comment by Alexsong111** [comment]
> > > Got it
> > 
> > 
> > Hi Qingkun, do you know how to do all the training all over again? Did you try it?
> > The author said we can go to notebooks, but the code is outdate and we need to change many things. Have you already change the code in notebooks? Thanks!
> 
> Try this https://github.com/xuqinkun/post_ocr_correction

Qingkun, I still cannot run it. Could you please try to run it with latest python version and give an example command? Thanks!

This is the command I use, is it correct?
python ./train/train_from_scratch.py -i ./train/data/ICDAR2019_POCR_compttition_dataset -ds SROIE  -m ./train/data/models/en/model_en.pt -o ./ --do_train --overwrite_model --overwrite_eval --overwrite_train
